'use strict';
(() => {
 const D=window.MAPA_COPY, app=document.getElementById('app');
 const requested=new URLSearchParams(location.search).get('lang');
 let lang=['pt','de'].includes(requested)?requested:D.defaultLanguage,stage='landing';
 let a={},person={name:'',day:'',month:'',year:'',city:'',email:'',hand:''},photo='',ticket=0,timer=0,error='',modal='',reading=0,round=0,reviewIndex=0,cameraStream=null,cameraRequest=0,express=false,offerTimer=0,stickyObserver=null;
 const session=window.MAPA_SESSION;
 let photoId='',restoring=true,scrollTimer=0,lastReadingSave=0;
 const readingTimings=[8000,8000,9000],readingRevealAt=[8,42,76];
 const reviews=D.testimonials.filter(r=>r.text&&r.name);
 const route=['relationship','goal','bridgeGoal','context','curiosity','bridgeQuestion','desire','connection',...(reviews.length?['reviews']:[]),'name','birth','city','photo','reading','obstacle','readiness','email','result'];
 const loc=x=>typeof x==='string'?x:x?.[lang]||'';
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const t=k=>esc(loc(D.copy[k]));
 const named=k=>t(k).replaceAll('{name}',esc(person.name));
 const branch=()=>D.branches[a.goal];
 const resultCopy=()=>a.desire==='curious'?branch().curiousResult:(branch().obstacles.find(r=>r.id===a.obstacle)?.result||{title:branch().resultTitle,lead:branch().resultLead});
 const money=(amount=D.price)=>new Intl.NumberFormat(lang==='pt'?'pt-BR':'de-DE',{style:'currency',currency:D.currenciesByLanguage[lang]}).format(amount);
 const btn=(action,text,cls='cta')=>`<button type="button" class="${cls}" data-action="${action}" ${action==='summary'?`data-purchase ${offerState().expired?'disabled':''}`:''}>${text}${cls==='cta'?'<span aria-hidden="true"> →</span>':''}</button>`;
 const eye=s=>`<p class="eyebrow">${s}</p>`;
 const label=(rows,id)=>esc(loc(rows?.find(r=>r.id===id)?.text));
 const answerLabel=k=>label(k==='desire'?D.desires:k==='goal'?D.goals:branch()?.[k],a[k]);
 const allReading=()=>['reading','obstacle','readiness'].includes(stage);
 function saveSession(){if(restoring)return;session.save({stage,lang,a,person,photoId,express,reading,round,reviewIndex,modal:modal==='camera'?'':modal,scrollY:window.scrollY});}
 async function restoreSession(){
  const saved=session.load();
  if(saved){
   if(['pt','de'].includes(saved.lang))lang=saved.lang;
   if(['landing','summary',...route].includes(saved.stage))stage=saved.stage;
   for(const k of Object.keys(person))if(typeof saved.person?.[k]==='string')person[k]=saved.person[k].slice(0,k==='email'?254:k==='city'?100:40);
   const pick=(key,rows)=>{const value=saved.a?.[key];if(rows?.some(row=>row.id===value))a[key]=value;};
   pick('relationship',D.relationships);pick('goal',D.goals);pick('desire',D.desires);pick('readiness',D.readiness);
   if(branch()){pick('context',branch().context);pick('curiosity',branch().curiosity);pick('obstacle',branch().obstacles);}
   // Resume at the earliest incomplete prerequisite if stored data is stale or invalid.
   const prerequisites=[['relationship',!!a.relationship],['goal',!!a.goal],['context',!!a.context],['curiosity',!!a.curiosity],['desire',!!a.desire],['name',!!person.name.trim()],['birth',!!(person.day&&person.month&&person.year)],['city',!!person.city.trim()]];
   for(const [step,complete] of prerequisites)if(!complete&&(stage==='summary'||route.indexOf(stage)>route.indexOf(step))){stage=step;break;}
   express=saved.express===true;
   round=Number.isInteger(saved.round)?Math.max(0,Math.min(2,saved.round)):0;
   reading=Number.isFinite(saved.reading)?Math.max([0,33,66][round],Math.min([33,66,100][round],saved.reading)):0;
   reviewIndex=Number.isInteger(saved.reviewIndex)&&saved.reviewIndex>=0?saved.reviewIndex:0;
   if(typeof saved.photoId==='string'&&/^[a-zA-Z0-9-]{1,80}$/.test(saved.photoId)){
    const blob=await session.getPhoto(saved.photoId);
    if(blob instanceof Blob&&['image/jpeg','image/png','image/webp'].includes(blob.type)&&blob.size<=10485760){photoId=saved.photoId;photo=URL.createObjectURL(blob);}
   }
   if(stage==='obstacle'&&round===0)modal='obstacle';
   else if(stage==='readiness'&&round===1)modal='readiness';
   else if(stage==='photo'&&photo&&saved.modal==='ready')modal='ready';
   if(allReading()&&!photo){stage='photo';modal='';}
  }
  restoring=false;render(false);
  if(saved&&Number.isFinite(saved.scrollY))requestAnimationFrame(()=>{window.scrollTo({top:Math.max(0,saved.scrollY),behavior:'instant'});saveSession();});
  session.cleanup();
 }
 function progress(){const n=route.indexOf(stage)+1;return `<div class="step-header">${btn('back','←','back')}<span>${lang==='pt'?'ETAPA':'SCHRITT'} <b>${n}</b> ${lang==='pt'?'DE':'VON'} ${route.length}</span><span class="step-percent">${Math.round(n/route.length*100)}%</span><div class="step-track" role="progressbar" aria-label="${lang==='pt'?'Seu progresso':'Dein Fortschritt'}" aria-valuemin="0" aria-valuemax="${route.length}" aria-valuenow="${n}"><i style="width:${n/route.length*100}%"></i></div></div>`;}
 function options(rows,k){return `<div class="choices">${rows.map(r=>`<button type="button" class="choice ${a[k]===r.id?'selected':''}" data-choice="${esc(k)}" data-value="${esc(r.id)}"><span class="radio" aria-hidden="true"></span><span>${esc(loc(r.text))}</span><span class="arrow" aria-hidden="true">›</span></button>`).join('')}</div>`;}
 function timeline(){return `<ol class="timeline">${D.timeline.map((r,i)=>`<li><span class="point">0${i+1}</span><div><h3>${esc(loc(r.title))}</h3><p>${esc(loc(r.text))}</p></div></li>`).join('')}</ol>`;}
 function handViz(animated=false,personal=false){
  const paths=personal?['M300 615 C375 595 430 607 484 622 C543 635 603 605 644 574','M337 742 C423 706 486 641 570 603 C614 585 650 563 667 541','M665 575 C577 638 532 719 550 809 C559 855 586 889 628 919']:['M322 675 C377 690 427 682 485 670 C560 660 648 633 684 571','M362 806 C447 764 564 705 648 688','M678 698 C594 737 559 817 548 876 C535 938 558 987 595 1025'];
  const points=personal?[[300,615],[484,622],[644,574],[337,742],[570,603],[628,919]]:[[322,675],[485,670],[684,571],[362,806],[648,688],[595,1025]];
  return `<figure class="hand-viz ${personal?'hand-final':''} ${animated?'animated':'settled'}"><div class="hand-art"><img src="assets/${personal?'mapa-final-rosa.png':'mapa-exemplo.png'}" alt="${t('exampleAlt')}" width="1122" height="1402"><div class="art-vignette"></div><svg viewBox="0 0 1122 1402" aria-hidden="true"><defs><filter id="glow"><feGaussianBlur stdDeviation="5"/></filter><linearGradient id="gold"><stop stop-color="#c28b37"/><stop offset=".55" stop-color="#f8d184"/><stop offset="1" stop-color="#b37d35"/></linearGradient></defs><g class="line-glow" filter="url(#glow)">${paths.map(d=>`<path d="${d}"/>`).join('')}</g><g class="traced-lines">${paths.map((d,i)=>`<path class="trace trace-${i+1}" pathLength="1" d="${d}"/>`).join('')}</g><g class="map-points">${points.map(([x,y],i)=>`<g class="map-dot" style="--delay:${i*.5}s"><circle class="pulse" cx="${x}" cy="${y}" r="18"/><circle cx="${x}" cy="${y}" r="6"/></g>`).join('')}</g></svg><span class="art-brand">HERZLINIEN</span><span class="art-title">${personal&&person.name?named('coverLabel'):t('product')}</span></div>${personal?`<figcaption class="cover-details"><strong>${esc(person.name)}</strong><span>${birthString()}${person.city?' · '+esc(person.city):''}</span></figcaption>`:''}</figure>`;
 }
 function creationSteps(){return `<section class="result-section creation-section" aria-labelledby="creation-title"><h2 id="creation-title">${t('creationTitle')}</h2><ol class="creation-stack">${[1,2,3].map(i=>`<li><div class="creation-thumb"><img src="assets/clara-creation-${i}.png" alt="" width="120" height="120" loading="lazy"><span aria-hidden="true">${i}</span></div><div class="creation-copy"><h3 ${i===3?'data-creation-delivery':''}>${t(i===3&&express?'creation3ExpressTitle':`creation${i}Title`)}</h3><p ${i===3?'data-creation-body':''}>${t(i===3&&express?'creation3ExpressBody':`creation${i}Body`)}</p></div></li>`).join('')}</ol></section>`;}
 function birthString(){return person.day&&person.month&&person.year?[person.day.padStart(2,'0'),person.month.padStart(2,'0'),person.year].map(esc).join(lang==='de'?'.':'/'):'';}
 function guide(){return `<div class="guide-small"><img src="assets/clara-natural-v2.png" alt="Clara" width="48" height="48"><div><strong>Clara</strong><span>${t('guideRole')}</span></div></div>`;}
 function testimonials(){if(!reviews.length)return '';const r=reviews[reviewIndex%reviews.length];return `<section class="testimonial-section">${eye(t('socialLabel'))}<h2>${t('socialTitle')}</h2><div class="testimonial-card">${r.image?`<img src="${esc(loc(r.image))}" alt="${esc(r.name+': '+loc(r.text))}">`:`<blockquote><p>${esc(loc(r.text))}</p><cite>${esc(r.name)}</cite></blockquote>`}</div><div class="review-dots" role="group" aria-label="${t('socialTitle')}">${reviews.map((r,i)=>`<button data-review="${i}" aria-label="${i+1}" aria-pressed="${i===reviewIndex}" class="${i===reviewIndex?'active':''}"></button>`).join('')}</div></section>`;}
 function faq(){return `<div class="faq">${D.faq.map(r=>`<details><summary>${esc(loc(r.q))}</summary><p>${esc(loc(r.a))}</p></details>`).join('')}</div>`;}
 function benefits(){return `<div class="benefits">${D.benefits.map((b,i)=>`<article><span class="number">0${i+1}</span><h3>${esc(loc(b.title))}</h3><p>${esc(loc(b.text))}</p></article>`).join('')}</div>`;}
 function inputField(field,labelText,type='text',extra=''){return `<label class="name-label" for="${field}">${labelText}</label><input id="${field}" name="${field}" type="${type}" value="${esc(person[field])}" ${extra} required>`;}
 function form(inner){return `<form id="step-form" novalidate>${inner}<p id="error" class="error" role="alert">${error?t(error):''}</p><button class="cta full" type="submit">${stage==='email'?t('emailCta'):stage==='photo'?t('prepare'):t('next')} <span aria-hidden="true">→</span></button></form>`;}
 function readingView(){return `<div class="reading-card"><h1>${person.name?esc(person.name)+', ':''}${t('readingTitle')}</h1><p>${t('readingLead')}</p><div class="reading-grid reading-summary"><div><div class="reading-status"><span>${t('readingLabel')}</span><strong id="reading-percent">${Math.floor(reading)}%</strong></div><div class="reading-track" role="progressbar" aria-label="${t('readingLabel')}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${Math.floor(reading)}"><i id="reading-fill" style="width:${reading}%"></i></div><div class="answer-stack">${[['answerSituation',answerLabel('context')],['answerWish',answerLabel('desire')],['answerQuestion',answerLabel('curiosity')]].map(([title,body],i)=>`<div class="answer-tile ${reading>=readingRevealAt[i]?'revealed':''}" data-reveal="${readingRevealAt[i]}"><span class="answer-check">✓</span><div>${eye(t(title))}<p>${body}</p></div></div>`).join('')}</div></div></div>${testimonials()}</div>`;}
 function dialog(){if(!modal)return '';if(modal==='camera')return `<dialog id="flow-dialog" class="camera-dialog" aria-labelledby="dialog-title"><div class="dialog-inner"><h2 id="dialog-title">${t('cameraTitle')}</h2><div class="camera-view"><video id="camera-preview" autoplay muted playsinline></video></div><p id="camera-status" role="status">${t('cameraLoading')}</p><button type="button" class="cta" data-action="capture-photo" disabled>${t('cameraCapture')}</button>${btn('close-modal',t('cancel'),'link')}</div></dialog>`;const ready=modal==='ready';return `<dialog id="flow-dialog" aria-labelledby="dialog-title"><div class="dialog-inner">${eye(ready?t('product'):t('duringLabel'))}<h2 id="dialog-title">${ready?t('readyTitle'):modal==='obstacle'?t('obstacleTitle'):t('readinessTitle')}</h2>${ready?`<p>${t('readyBody')}</p>${btn('begin-reading',t('beginReading'))}${btn('close-modal',t('cancel'),'link')}`:options(modal==='obstacle'?branch().obstacles:D.readiness,modal)}</div></dialog>`;}
 function render(focus=true){stopCamera();clearInterval(timer);clearInterval(offerTimer);stickyObserver?.disconnect();document.body.classList.toggle('has-sticky-offer',stage==='result');document.documentElement.lang=lang==='pt'?'pt-BR':'de';document.title='Herzlinien · '+loc(D.copy.product);document.getElementById('header').innerHTML=`<span class="brand" translate="no">herzlinien ✧</span><div class="language"><label for="language">${t('review')}</label><select id="language"><option value="de" ${lang==='de'?'selected':''}>Deutsch</option><option value="pt" ${lang==='pt'?'selected':''}>Português</option></select></div>`;document.getElementById('demo-note').textContent=loc(D.copy.demo);document.getElementById('footer').innerHTML=`<div class="footer-brand"><span class="brand" translate="no">herzlinien✧</span><p>${t('futureNote')}</p></div>`;
 app.className=stage==='landing'?'landing':`flow v4-flow ${stage}`;let h='';
 if(stage==='landing'){h=`<section class="hero"><div class="hero-copy">${eye(t('product'))}<h1>${t('headline')}</h1><p class="lead">${t('lead')}</p><p class="sublead">${t('sublead')}</p>${btn('start',t('start'))}<p class="small">${t('free')}</p></div>${handViz(true)}</section><section class="section">${eye(t('included'))}<h2>${t('exampleTitle')}</h2>${benefits()}<p class="included-delivery">${t('includedDelivery')}</p></section>${testimonials()}<section class="section faq-section"><h2>${lang==='pt'?'Antes de começar':'Bevor du beginnst'}</h2>${faq()}</section><div class="closing"><h2>${t('bottomTitle')}</h2>${btn('start',t('start'))}</div>`;}
 else if(['relationship','goal','context','curiosity','desire'].includes(stage)){const title=stage==='relationship'?t('relationshipTitle'):stage==='goal'?esc(loc(D.questions[0])):stage==='context'?esc(loc(branch().question)):stage==='curiosity'?esc(loc(D.questions[2])):t('desireTitle');const rows=stage==='relationship'?D.relationships:stage==='goal'?D.goals:stage==='desire'?D.desires:branch()[stage];h=`${progress()}<section class="question-body"><h1>${title}</h1>${options(rows,stage)}</section>`;}
 else if(['bridgeGoal','bridgeQuestion','connection'].includes(stage)){let title,body;if(stage==='bridgeGoal'){title=esc(loc(D.bridges[a.goal].title));body=esc(loc(D.bridges[a.goal].body));}else if(stage==='bridgeQuestion'){title=esc(loc(branch().questionBridge.title));body=esc(loc(branch().questionBridge.body));}else {title=t('connectionTitle');body=esc(loc(D.desires.find(r=>r.id===a.desire).response));}h=`${progress()}<section class="connection-screen"><div class="connection-art" aria-hidden="true"><span>✧</span><i></i><i></i></div>${eye(t('bridgeEyebrow'))}<h1>${title}</h1><p class="lead">${body}</p>${guide()}${btn('next',t('next'))}</section>`;}
 else if(stage==='reviews'){h=`${progress()}${testimonials()}${btn('next',t('next'))}`;}
 else if(stage==='name'){h=`${progress()}<section class="question-body">${eye(t('personalIntro'))}<h1>${t('nameTitle')}</h1><p>${t('nameHelp')}</p>${form(inputField('name',t('nameLabel'),'text','maxlength="40" autocomplete="given-name"'))}</section>`;}
 else if(stage==='birth'){h=`${progress()}<section class="question-body"><h1>${t('birthTitle')}</h1><p>${t('birthHelp')}</p>${form(`<div class="date-fields">${[['day',31,2],['month',12,2],['year',new Date().getFullYear(),4]].map(([k,max,length])=>`<div>${inputField(k,t(k),'number',`min="${k==='year'?1900:1}" max="${max}" inputmode="numeric" placeholder="${k==='year'?'1990':k==='month'?'05':'15'}"`)}</div>`).join('')}</div>`)}</section>`;}
 else if(stage==='city'){h=`${progress()}<section class="question-body"><h1>${t('cityTitle')}</h1><p>${t('cityHelp')}</p>${form(inputField('city',t('cityLabel'),'text',`maxlength="100" autocomplete="off" placeholder="${t('cityPlaceholder')}"`))}</section>`;}
 else if(stage==='photo'){h=`${progress()}<section class="question-body"><h1>${t('photoTitle')}</h1><p>${t('photoLead')}</p>${form(`<figure class="photo-example"><img src="assets/como-fotografar-mao.svg" width="260" height="300" alt="${t('photoExampleAlt')}"><figcaption><h2>${t('photoExample')}</h2><ul><li>${t('photoTip1')}</li><li>${t('photoTip2')}</li><li>${t('photoTip3')}</li></ul></figcaption></figure><div class="photo-actions"><button type="button" class="cta photo-camera" data-action="take-photo"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 5 10 3h4l2 2h4a2 2 0 0 1 2 2v12H2V7a2 2 0 0 1 2-2Z"/><circle cx="12" cy="12" r="4"/></svg>${t('takePhoto')}</button><button type="button" class="secondary" data-action="choose-photo">${t('gallery')}</button><input id="camera-upload" type="file" accept="image/*" capture="environment" hidden><input id="upload" type="file" accept="image/jpeg,image/png,image/webp" hidden><p class="small">${t('formats')}</p></div>${photo?`<div class="selected-photo"><img src="${photo}" alt="${t('photoAlt')}">${btn('remove-photo',t('removePhoto'),'link')}</div>`:''}<fieldset><legend>${t('hand')}</legend><div class="hand-options">${['right','left'].map(k=>`<label><input type="radio" name="hand" value="${k}" ${person.hand===k?'checked':''}>${t(k)}</label>`).join('')}</div></fieldset><p class="privacy-inline">${t('photoLocal')}</p>`)}</section>`;}
 else if(allReading()){h=`${progress()}${readingView()}`;}
 else if(stage==='email'){h=`${progress()}<section class="question-body">${eye(named('coverLabel'))}<h1>${t('emailTitle')}</h1><p>${t('emailHelp')}</p>${form(inputField('email',t('emailLabel'),'email','maxlength="254" autocomplete="email" placeholder="nome@exemplo.com"')+`<p class="privacy-inline">${t('emailLocal')}</p>`)}</section>`;}
 else if(stage==='result'){h=`${stickyOffer()}<section class="result-hero"><h1>${esc(loc(resultCopy().title)).replaceAll('{name}',()=>esc(person.name))}</h1><p class="lead">${esc(loc(resultCopy().lead))}</p>${handViz(true,true)}${btn('scroll-offer',t('resultCta'))}<div class="result-message">${guide()}${a.desire==='curious'?`<p>${esc(loc(D.desires.find(r=>r.id==='curious').response))}</p>`:`${a.relationship!=='private'?`<p>${esc(loc(D.relationships.find(r=>r.id===a.relationship)?.response))}</p>`:''}<p>${esc(loc(branch().obstacles.find(r=>r.id===a.obstacle)?.response))}</p>`}</div></section><section class="result-section"><h2>${t('howTitle')}</h2><p class="product-explanation">${t('howLead')}</p></section>${creationSteps()}${testimonials()}<section class="result-section"><h2>${t('offerTitle')}</h2>${timeline()}<div class="personal-chapter">${eye(t('offerFocusTitle'))}<h3>${esc(loc(branch().chapter))}</h3><p>${esc(loc(D.desires.find(r=>r.id===a.desire).response))}</p></div></section>${offerCard()}${guaranteeCard()}${faq()}${btn('restart',t('restart'),'link')}`;}
 else if(stage==='summary'){h=`<h1>${t('summaryTitle')}</h1><div class="summary-card"><div><h2>${t('product')}</h2><p>${esc(loc(branch().chapter))}</p><p>${t('oneTime')}</p><p>${t(express?'expressDelivery':'standardDescription')}</p><p>${t('guaranteeBadge')}</p><p>${t('yourDetails')}: ${esc(person.name)} · ${birthString()} · ${esc(person.city)}</p><p>${esc(person.email)}</p></div><div><span class="small">${t('total')}</span><p class="price">${esc(money(offerState().total))}</p>${express?`<p class="small">${t('expressTitle')}: + ${esc(money(D.offer.expressPrice))}</p>`:''}</div></div><p class="notice" role="status">${offerState().expired?t('summaryUnavailable'):t('summaryNotice')}</p><div class="nav">${btn('result',t('change'),'secondary')}${btn('restart',t('restart'),'link')}</div>`;}
 app.innerHTML=h+dialog();if(focus){window.scrollTo({top:0,behavior:'instant'});const heading=app.querySelector('h1');if(heading){heading.tabIndex=-1;heading.focus({preventScroll:true});}}
 if(modal){const dlg=document.getElementById('flow-dialog');dlg.showModal();dlg.addEventListener('cancel',e=>{if(!['ready','camera'].includes(modal)){e.preventDefault();return;}modal='';render(false);});dlg.querySelector('button:not([disabled])')?.focus();}
 else if(allReading())animateReading();
 saveSession();
 if(stage==='result'){updateOfferClock();offerTimer=setInterval(updateOfferClock,1000);const bar=document.getElementById('sticky-offer');stickyObserver=new ResizeObserver(()=>document.documentElement.style.setProperty('--offer-bar-height',bar.offsetHeight+'px'));stickyObserver.observe(bar);}
 }
 function go(s){clearInterval(timer);stage=s;error='';modal='';render();}
 function next(){go(route[route.indexOf(stage)+1]);}
 function showError(k){error=k;const e=document.getElementById('error');if(e){e.textContent=loc(D.copy[k]);e.scrollIntoView({block:'nearest'});}}
 function validate(){if(stage==='name'||stage==='city'){const k=stage==='name'?'name':'city';person[k]=person[k].trim();return person[k].length>0||'fieldRequired';}if(stage==='birth'){const day=Number(person.day),month=Number(person.month),year=Number(person.year),birth=new Date(year,month-1,day),now=new Date();if(!day||!month||!year||year<1900||year>now.getFullYear()||birth.getFullYear()!==year||birth.getMonth()!==month-1||birth.getDate()!==day||birth>now)return 'invalidDate';const adult=new Date(now.getFullYear()-18,now.getMonth(),now.getDate());return birth<=adult||'adultOnly';}if(stage==='photo')return photo?(person.hand?true:'handError'):'photoNeeded';if(stage==='email'){person.email=person.email.trim();return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(person.email)&&document.getElementById('email').validity.valid||'invalidEmail';}return true;}
 function animateReading(){const target=[33,66,100][round],start=reading,started=performance.now(),duration=matchMedia('(prefers-reduced-motion: reduce)').matches?100:Math.max(100,readingTimings[round]*(target-start)/[33,33,34][round]);timer=setInterval(()=>{reading=Math.min(target,start+(target-start)*(performance.now()-started)/duration);const n=document.getElementById('reading-percent'),f=document.getElementById('reading-fill');if(n)n.textContent=Math.floor(reading)+'%';if(f){f.style.width=reading+'%';f.parentElement.setAttribute('aria-valuenow',Math.floor(reading));}app.querySelectorAll('[data-reveal]').forEach(e=>e.classList.toggle('revealed',reading>=Number(e.dataset.reveal)));if(performance.now()-lastReadingSave>500){saveSession();lastReadingSave=performance.now();}if(reading>=target){clearInterval(timer);if(round===0){stage='obstacle';modal='obstacle';render(false);}else if(round===1){stage='readiness';modal='readiness';render(false);}else go('email');}},40);}

 function stopCamera(){cameraRequest++;if(cameraStream){cameraStream.getTracks().forEach(track=>track.stop());cameraStream=null;}}
 function acceptPhoto(file){if(!file)return;const id=++ticket;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10485760){showError('photoError');return;}const url=URL.createObjectURL(file),image=new Image();image.onload=async()=>{if(id!==ticket){URL.revokeObjectURL(url);return;}const nextId=crypto.randomUUID(),stored=await session.putPhoto(nextId,file);if(id!==ticket){URL.revokeObjectURL(url);if(stored)session.removePhoto(nextId);return;}const previousId=photoId;if(photo)URL.revokeObjectURL(photo);photo=url;photoId=stored?nextId:'';error='';saveSession();session.removePhoto(previousId);if(stage==='photo')render(false);};image.onerror=()=>{URL.revokeObjectURL(url);if(id===ticket)showError('decodeError');};image.src=url;}
 async function openCamera(){
  const mobile=/Android|iPhone|iPad|iPod/i.test(navigator.userAgent)||(/Macintosh/.test(navigator.userAgent)&&navigator.maxTouchPoints>1);
  if(mobile){document.getElementById('camera-upload').click();return;}
  if(!navigator.mediaDevices?.getUserMedia){showError('cameraUnavailable');return;}
  modal='camera';render(false);const id=++cameraRequest;
  try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:960}},audio:false});
   if(id!==cameraRequest||stage!=='photo'||modal!=='camera'){stream.getTracks().forEach(track=>track.stop());return;}
   cameraStream=stream;const video=document.getElementById('camera-preview');video.srcObject=stream;await video.play();
   if(id!==cameraRequest)return;
   document.getElementById('camera-status').textContent=loc(D.copy.cameraReady);document.querySelector('[data-action="capture-photo"]').disabled=false;
  }catch(err){if(id!==cameraRequest)return;modal='';render(false);showError(err.name==='NotAllowedError'?'cameraDenied':'cameraUnavailable');}
 }
 function capturePhoto(){
  const video=document.getElementById('camera-preview');if(!video?.videoWidth||!video.videoHeight)return;
  const canvas=document.createElement('canvas');canvas.width=video.videoWidth;canvas.height=video.videoHeight;
  canvas.getContext('2d').drawImage(video,0,0);const id=cameraRequest;document.querySelector('[data-action="capture-photo"]').disabled=true;
  canvas.toBlob(blob=>{if(id!==cameraRequest)return;modal='';render(false);if(blob)acceptPhoto(blob);else showError('cameraUnavailable');},'image/jpeg',.92);
 }

 function offerState(){return window.MAPA_OFFER.getOfferState(D.offer,D.price,express);}
 function offerDate(){const [y,m,d]=D.offer.availability.date.split('-');return lang==='pt'?`${d}/${m}/${y}`:`${d}.${m}.${y}`;}
 function availabilityText(){return t(offerState().expired?'availabilityExpired':'availabilityLabel').replaceAll('{date}',offerDate());}
 function stickyOffer(){return `<aside id="sticky-offer" class="sticky-offer" aria-label="${t('priceLabel')}"><div class="sticky-inner"><div class="sticky-timing"><strong data-availability>${availabilityText()}</strong><span data-countdown-wrap ${offerState().expired?'hidden':''}><span data-countdown-label>${t('availabilityEnds')}</span> <b data-countdown>${offerState().clock}</b> <small>(${lang==='pt'?'Berlim':'Berlin'})</small></span></div><button type="button" class="cta" data-action="scroll-offer"><span data-sticky-label>${t(offerState().expired?'stickyExpired':'stickyBuy')}</span></button></div></aside>`;}
 function referenceState(){return window.MAPA_OFFER.getReferenceState(D.offer,D.price,express);}
 function savingsText(){return referenceState()?t('packageSavings').replace('{amount}',esc(money(referenceState().savings))):'';}
 function packageItemPrice(key,i){if(!referenceState())return `<strong>${t('includedLabel')}</strong>`;const original=D.offer.referencePrices[key];return `<span class="item-pricing">${original?`<del>${esc(money(original))}</del>`:''}<strong class="${i===0?'':'included-price'}">${esc(money(i===0?D.price:0))}</strong></span>`;}
 function offerCard(){return `<section id="packageSection" class="result-section purchase-section"><h2>${t('offerHeading')}</h2><p class="offer-stack-lead">${t('offerStackLead')}</p><div class="package-card"><div class="availability-pill" data-availability>${availabilityText()}</div><div class="package-value"><p class="eyebrow">${t('packageValueTitle')}</p><h3>${t('packageValueBody')}</h3>${referenceState()?`<p class="package-reference">${t('separateValue')}: <del>${esc(money(referenceState().base))}</del></p><span class="package-price-label">${t('packagePriceLabel')}</span>`:''}<strong class="package-base-price">${esc(money())}</strong>${referenceState()?`<p class="package-savings">${savingsText()}</p>`:''}<p>${t('packageValueNote')}</p></div><ul class="package-items">${['packageMap','packagePdf','packageFocus','packageAudio','packageEmail'].map((key,i)=>`<li><span class="item-check" aria-hidden="true">✓</span><span>${t(key)}</span>${packageItemPrice(key,i)}</li>`).join('')}</ul><label class="express-option"><input id="express-option" type="checkbox" ${express?'checked':''}><span><strong>ϟ ${t('expressTitle')}</strong><small>${t('expressDescription')}</small></span><b>+ ${esc(money(D.offer.expressPrice))}</b></label><div class="package-total"><strong>${t('orderTotal')}</strong><span class="total-prices">${referenceState()?`<del data-reference-total aria-label="${t('separateValue')}">${esc(money(referenceState().total))}</del>`:''}<strong data-order-total>${esc(money(offerState().total))}</strong></span></div>${referenceState()?`<p class="package-savings total-savings">${savingsText()}</p>`:''}<p class="delivery-note" data-delivery>${t(express?'expressDelivery':'standardDescription')}</p>${btn('summary',t('purchaseCta'))}<p class="purchase-expired" data-expiry-note ${offerState().expired?'':'hidden'}>${t('availabilityExpiredBody').replaceAll('{date}',offerDate())}</p><div class="package-trust"><strong>✓ ${t('guaranteeBadge')}</strong><span>${t('noSubscription')}</span></div><p class="small purchase-demo">${t('notLive')}</p></div></section>`;}
 function guaranteeCard(){return `<section class="guarantee-card"><span class="guarantee-seal" aria-hidden="true">✓</span><div>${eye(t('guaranteeBadge'))}<h2>${t('guaranteeTitle')}</h2><p>${t('guaranteeBody')}</p><details><summary>${t('guaranteeDetails')}</summary><p>${t('guaranteeSteps')}</p></details></div></section>`;}
 function refreshOfferPrices(){const state=offerState();if(referenceState())app.querySelectorAll('[data-reference-total]').forEach(e=>e.textContent=money(referenceState().total));app.querySelectorAll('[data-creation-body]').forEach(e=>e.textContent=loc(D.copy[express?'creation3ExpressBody':'creation3Body']));app.querySelectorAll('[data-creation-delivery]').forEach(e=>e.textContent=loc(D.copy[express?'creation3ExpressTitle':'creation3Title']));app.querySelectorAll('[data-order-total]').forEach(e=>e.textContent=money(state.total));app.querySelectorAll('[data-delivery]').forEach(e=>e.textContent=loc(D.copy[express?'expressDelivery':'standardDescription']));}
 function updateOfferClock(){const state=offerState();app.querySelectorAll('[data-countdown-wrap]').forEach(e=>e.hidden=state.expired);app.querySelectorAll('[data-sticky-label]').forEach(e=>e.textContent=loc(D.copy[state.expired?'stickyExpired':'stickyBuy']));app.querySelectorAll('[data-countdown]').forEach(e=>e.textContent=state.clock);app.querySelectorAll('[data-availability]').forEach(e=>e.textContent=availabilityText());app.querySelectorAll('[data-purchase]').forEach(e=>e.disabled=state.expired);app.querySelectorAll('[data-expiry-note]').forEach(e=>e.hidden=!state.expired);app.querySelectorAll('[data-countdown-label]').forEach(e=>e.hidden=state.expired);document.getElementById('sticky-offer')?.classList.toggle('expired',state.expired);}
 function reset(){session.clear();session.removePhoto(photoId);photoId='';express=false;clearInterval(timer);ticket++;if(photo)URL.revokeObjectURL(photo);photo='';a={};person={name:'',day:'',month:'',year:'',city:'',email:'',hand:''};round=0;reading=0;go('landing');}
 app.addEventListener('submit',e=>{e.preventDefault();const valid=validate();if(valid!==true){showError(valid);return;}if(stage==='photo'){modal='ready';render(false);}else next();});
 app.addEventListener('input',e=>{if(Object.hasOwn(person,e.target.name)&&e.target.name!=='hand'){person[e.target.name]=e.target.value;saveSession();}});
 app.addEventListener('click',e=>{const choice=e.target.closest('[data-choice]');if(choice){const k=choice.dataset.choice,v=choice.dataset.value;if(k==='relationship'&&a.relationship!==v){delete a.context;delete a.curiosity;delete a.obstacle;}if(k==='goal'&&a.goal!==v){delete a.context;delete a.curiosity;delete a.obstacle;}a[k]=v;if(k==='obstacle'||k==='readiness'){round=k==='obstacle'?1:2;modal='';render(false);}else next();return;}const review=e.target.closest('[data-review]');if(review){reviewIndex=Number(review.dataset.review);render(false);return;}const action=e.target.closest('[data-action]')?.dataset.action;if(!action)return;if(action==='summary'&&offerState().expired){updateOfferClock();return;}if(action==='take-photo')openCamera();else if(action==='choose-photo')document.getElementById('upload').click();else if(action==='capture-photo')capturePhoto();else if(action==='start')go('relationship');else if(action==='next')next();else if(action==='back'){if(allReading())go('photo');else {const previous=route[route.indexOf(stage)-1];if(['reading','obstacle','readiness'].includes(previous))go('photo');else go(previous||'landing');}}else if(action==='begin-reading'){round=0;reading=0;go('reading');}else if(action==='close-modal'){modal='';render(false);}else if(action==='remove-photo'){session.removePhoto(photoId);photoId='';ticket++;if(photo)URL.revokeObjectURL(photo);photo='';render(false);}else if(action==='scroll-offer'){document.getElementById('packageSection').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}else if(action==='summary'||action==='result')go(action);else if(action==='restart')reset();});
 app.addEventListener('change',e=>{if(e.target.id==='express-option'){express=e.target.checked;refreshOfferPrices();saveSession();return;}if(e.target.name==='hand'){person.hand=e.target.value;saveSession();}if(['upload','camera-upload'].includes(e.target.id))acceptPhoto(e.target.files[0]);});
 document.getElementById('header').addEventListener('change',e=>{if(e.target.id==='language'){lang=e.target.value;render(false);document.getElementById('language').focus();}});
 window.addEventListener('scroll',()=>{clearTimeout(scrollTimer);scrollTimer=setTimeout(saveSession,150);},{passive:true});
 document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')saveSession();});
 window.addEventListener('pagehide',()=>{saveSession();stopCamera();clearInterval(timer);clearInterval(offerTimer);stickyObserver?.disconnect();ticket++;if(photo)URL.revokeObjectURL(photo);});
 app.setAttribute('aria-busy','true');app.textContent=lang==='pt'?'Carregando seu mapa…':'Deine Karte wird geladen…';
 restoreSession().finally(()=>app.removeAttribute('aria-busy'));
})();
