from pathlib import Path
import re
p=Path('outputs/preview-quiz-herzlinien.html');s=p.read_text();Path('work/landing-before-reference.html').write_text(s)
s=re.sub(r'<header>.*?</header>','',s,count=1,flags=re.S)
s=s.replace('<section class="promise-hero"><div class="eyebrow">Deine persönliche Liebeslandkarte</div>','<section class="promise-hero"><div class="intro-person"><img src="clara-falk-retrato-v1.png" alt="Clara Falk, virtuelle Begleiterin" width="56" height="56"><div><strong>Deine Liebeslandkarte mit Clara</strong><span>Für deine Geschichte und deinen nächsten Schritt in der Liebe.</span></div></div>')
s=s.replace('<p class="method">Aus deinen Antworten und einer symbolischen Deutung deiner Handlinien.</p>','<div class="product-badge"><span>Dein Handfoto</span><i aria-hidden="true">·</i><span>Deine persönliche Deutung</span></div>')
s=s.replace('<p class="small example-caption">Illustrative Darstellung des Handlinien-Mappings. Kein persönliches Analyseergebnis.</p>','')
s=s.replace('<p class="small">Beantworte ein paar Fragen und lade anschließend dein Handfoto hoch.<br>Quiz und Vorschau kostenlos · Vollständige Liebeslandkarte ab 34,90 €</p>','<p class="small price-note">Test und Vorschau gratis · Vollständige Liebeslandkarte ab 34,90 €</p>')
s=s.replace("if(step===-1){h=", "if(step===-1){app.className='landing-page';h=")
css='''
/* Entry-page structure adapted from the supplied reference. */
main.landing-page{max-width:none;padding:0;margin:0}main:not(.landing-page){padding-top:50px}h1:focus{outline:none}.landing-page{color:#1f2937}.landing-page .promise-hero{max-width:none;margin:0;padding:58px 28px 60px;background:linear-gradient(180deg,#fce7f3 0%,#fdf0f7 80%,#fff7fb 100%);text-align:center}.intro-person{display:flex;align-items:center;justify-content:center;gap:13px;text-align:left;margin:0 auto 28px;max-width:660px}.intro-person img{height:56px;width:56px;object-fit:cover;border-radius:50%;border:3px solid white}.intro-person strong{display:block;font-size:16px;font-weight:650;color:#29252d}.intro-person span{display:block;font-size:14px;line-height:1.5;color:#68616a}.landing-page .promise-hero h1{font-family:Arial,Helvetica,sans-serif;font-size:clamp(38px,5.2vw,76px);font-weight:750;line-height:1.08;letter-spacing:-2px;max-width:1220px;margin:0 auto 28px;color:#1f2937}.landing-page .lead{font-size:clamp(18px,2.15vw,27px);font-weight:450;line-height:1.5;max-width:1100px;margin:0 auto 26px;color:#4b5563}.product-badge{display:inline-flex;align-items:center;justify-content:center;gap:14px;background:#ffffffed;padding:12px 25px;border-radius:40px;box-shadow:0 5px 22px #54213d0c;font-size:15px;font-weight:550;color:#4b5563;margin-bottom:28px}.product-badge i{font-style:normal;color:#c98bad}.landing-page .product-preview{margin:0 auto 28px;max-width:660px;background:#fff;border:1px solid #f0dce7;box-shadow:0 18px 48px #6d23421a;border-radius:14px}.landing-page .product-preview>img{min-height:340px}.landing-page .product-copy{padding:28px}.landing-page .product-copy h2{color:#1f2937}.landing-page .cta{background:#cf4388;color:white;border-radius:10px;padding:18px 30px;box-shadow:0 6px 18px #ba347f25;font-size:18px;min-width:340px}.landing-page .cta:hover{background:#b82f74}.landing-page .audience-copy{font-size:15px;color:#62616b;max-width:670px;margin:18px auto 12px}.landing-page .price-note{font-size:14px;color:#61616b;margin:0}.landing-page>.landing-section{max-width:1080px;margin:0 auto;padding:70px 30px;border-top:0}.landing-page .landing-section h2{font-family:Arial,Helvetica,sans-serif;font-size:clamp(30px,3.6vw,44px);font-weight:700;letter-spacing:-1px;color:#1f2937}.landing-page .landing-section>h2,.landing-page .landing-section>.eyebrow{text-align:center}.landing-page>.clara-section{max-width:1020px;margin:0 auto;background:#fff0f7;border:1px solid #f4d9e7}.landing-page>.faq{max-width:820px}.landing-page .closing{background:#fce7f3;border-radius:16px;padding:36px 20px;margin-top:40px}.landing-page .eyebrow{color:#a64c7d}.landing-page details{border-color:#e8dae2}.landing-page .benefit-grid{gap:28px}.landing-page .benefit-grid article{background:#fff;padding:25px;border:1px solid #eee4e9;border-radius:12px}.landing-page .benefit-grid h3{color:#293242}.landing-page .clara-section h2{font-family:Arial,Helvetica,sans-serif;font-weight:650;font-size:34px;line-height:1.15}.landing-page .clara-section p{color:#4b5563}
@media(min-width:1500px){.landing-page .promise-hero{padding-top:65px}.landing-page .promise-hero h1{font-size:80px}}
@media(max-width:650px){.landing-page .promise-hero{padding:30px 18px 38px}.intro-person{gap:10px;margin-bottom:24px}.intro-person img{height:46px;width:46px}.intro-person strong{font-size:14px}.intro-person span{font-size:12px}.landing-page .promise-hero h1{font-size:38px;letter-spacing:-1.2px;line-height:1.1;margin-bottom:20px}.landing-page .lead{font-size:18px;line-height:1.5}.product-badge{font-size:13px;gap:10px;padding:10px 14px}.landing-page .product-copy{padding:16px 12px}.landing-page .product-preview>img{min-height:290px}.landing-page .product-copy h2{font-size:25px}.landing-page .cta{min-width:0;width:100%;font-size:16px;padding:17px 14px}.landing-page .price-note{font-size:13px}.landing-page>.landing-section{padding:45px 20px}.landing-page>.clara-section{margin:0 20px;padding:25px}.landing-page .benefit-grid article{padding:22px}.landing-page .clara-section h2{font-size:29px}}
'''
s=s.replace('</style>',css+'</style>')
p.write_text(s)
print('Cabeçalho removido; hero rosa e centralizado; legenda removida; microcopy substituída; seções alinhadas à referência.')
